/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.gnuradio.controlport;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum KnobType implements org.apache.thrift.TEnum {
  KNOBBOOL(0),
  KNOBCHAR(1),
  KNOBINT(2),
  KNOBDOUBLE(3),
  KNOBSTRING(4),
  KNOBLONG(5),
  KNOBVECBOOL(6),
  KNOBVECCHAR(7),
  KNOBVECINT(8),
  KNOBVECDOUBLE(9),
  KNOBVECSTRING(10),
  KNOBVECLONG(11),
  KNOBSHORT(12);

  private final int value;

  private KnobType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static KnobType findByValue(int value) { 
    switch (value) {
      case 0:
        return KNOBBOOL;
      case 1:
        return KNOBCHAR;
      case 2:
        return KNOBINT;
      case 3:
        return KNOBDOUBLE;
      case 4:
        return KNOBSTRING;
      case 5:
        return KNOBLONG;
      case 6:
        return KNOBVECBOOL;
      case 7:
        return KNOBVECCHAR;
      case 8:
        return KNOBVECINT;
      case 9:
        return KNOBVECDOUBLE;
      case 10:
        return KNOBVECSTRING;
      case 11:
        return KNOBVECLONG;
      case 12:
        return KNOBSHORT;
      default:
        return null;
    }
  }
}
